package fix

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"stackaudit/internal/docker"
	"stackaudit/internal/env"
	"stackaudit/internal/rules"
	"stackaudit/internal/utils"
)

type Action struct {
	ID          string
	Description string
	Files       []string
	Apply       func() error
}

type Plan struct {
	Actions []Action
	Notes   []string
}

type Result struct {
	Description string
	Error       error
}

func BuildPlan(ctx context.Context, root string, ruleSet rules.RuleSet) (Plan, error) {
	plan := Plan{}
	ignore, err := utils.LoadIgnoreMatcher(root)
	if err != nil {
		return plan, err
	}

	envReport, err := env.Scan(ctx, root, ruleSet)
	if err != nil {
		return plan, err
	}

	plan.Notes = append(plan.Notes, "Fixes run locally and never upload data.")
	plan.Notes = append(plan.Notes, "Review backups created alongside modified files.")

	plan.Actions = append(plan.Actions, buildEnvExampleAction(root, envReport, ignore)...)
	plan.Actions = append(plan.Actions, buildEnvCleanupActions(envReport)...)
	plan.Actions = append(plan.Actions, buildComposeRestartAction(root, ignore)...)

	return plan, nil
}

func ApplyPlan(plan Plan) []Result {
	results := []Result{}
	for _, action := range plan.Actions {
		err := action.Apply()
		results = append(results, Result{
			Description: action.Description,
			Error:       err,
		})
	}
	return results
}

func buildEnvExampleAction(root string, report env.Report, ignore utils.IgnoreMatcher) []Action {
	target := filepath.Join(root, ".env.example")
	if ignore != nil && ignore(target, false) {
		return nil
	}
	if _, err := os.Stat(target); err == nil {
		return nil
	}

	return []Action{
		{
			ID:          "env_example",
			Description: "Generate .env.example from existing env files",
			Files:       []string{target},
			Apply: func() error {
				keys := map[string]bool{}
				for _, file := range report.Files {
					if file.IsExample {
						continue
					}
					for key := range file.Vars {
						keys[key] = true
					}
				}
				content := "# Generated by StackAudit\n"
				for key := range keys {
					content += fmt.Sprintf("%s=\n", key)
				}
				return os.WriteFile(target, []byte(content), 0o644)
			},
		},
	}
}

func buildEnvCleanupActions(report env.Report) []Action {
	actions := []Action{}
	for path, unused := range report.UnusedVars {
		filePath := path
		vars := append([]string{}, unused...)
		actions = append(actions, Action{
			ID:          "remove_unused",
			Description: fmt.Sprintf("Remove unused env vars from %s", filepath.Base(path)),
			Files:       []string{filePath},
			Apply: func() error {
				return removeUnusedFromEnv(filePath, vars)
			},
		})
	}
	return actions
}

func buildComposeRestartAction(root string, ignore utils.IgnoreMatcher) []Action {
	composePath := filepath.Join(root, "docker-compose.yml")
	if ignore != nil && ignore(composePath, false) {
		return nil
	}
	if _, err := os.Stat(composePath); err != nil {
		return nil
	}
	return []Action{
		{
			ID:          "compose_restart",
			Description: "Add restart policy to docker-compose.yml services",
			Files:       []string{composePath},
			Apply: func() error {
				return docker.AddRestartPolicies(composePath)
			},
		},
	}
}

func removeUnusedFromEnv(path string, unused []string) error {
	backup := fmt.Sprintf("%s.bak.%d", path, time.Now().Unix())
	data, err := os.ReadFile(path)
	if err != nil {
		return err
	}
	if err := os.WriteFile(backup, data, 0o644); err != nil {
		return err
	}

	lines := strings.Split(string(data), "\n")
	filtered := []string{}
	for _, line := range lines {
		trimmed := strings.TrimSpace(line)
		if trimmed == "" || strings.HasPrefix(trimmed, "#") {
			filtered = append(filtered, line)
			continue
		}
		parts := strings.SplitN(trimmed, "=", 2)
		key := strings.TrimSpace(parts[0])
		if contains(unused, key) {
			continue
		}
		filtered = append(filtered, line)
	}

	return os.WriteFile(path, []byte(strings.Join(filtered, "\n")), 0o644)
}

func contains(values []string, target string) bool {
	for _, value := range values {
		if value == target {
			return true
		}
	}
	return false
}
