project_name: stack

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - "386"
    main: ./cmd/stack
    ldflags:
      - -s -w -X stack/pkg/version.version={{.Version}} -X stack/pkg/version.commit={{.Commit}} -X stack/pkg/version.date={{.Date}} -X stack/pkg/version.builtBy=goreleaser

archives:
  - name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

nfpms:
  - file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    vendor: StackAudit
    homepage: https://github.com/neutron420/StackAudit
    maintainer: neutron420 <support@stackaudit.io>
    description: The Local-First Backend Health & Security Audit Tool
    license: MIT
    formats:
      - deb
      - rpm

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  github:
    owner: neutron420
    name: StackAudit
  draft: false
  prerelease: auto
